@echo off
echo Adding all changes...
git add .
echo Committing changes...
git commit -m "Enhance Admin Dashboard editing and add Vendor Profile page"
echo Pushing to GitHub...
git push https://github.com/jjuliano717-DBA/wedding-flow-pro.git main
pause
